// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api_gateway/ad/v1/ad.proto

package adV1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Use enums — never strings for finite state
// Strings: no validation, typo-prone, no exhaustive switch in Go
type AdStatus int32

const (
	AdStatus_AD_STATUS_UNSPECIFIED AdStatus = 0 // always define a zero value
	AdStatus_AD_STATUS_ACTIVE      AdStatus = 1
	AdStatus_AD_STATUS_SOLD        AdStatus = 2
	AdStatus_AD_STATUS_BANNED      AdStatus = 3
	AdStatus_AD_STATUS_INACTIVE    AdStatus = 4
)

// Enum value maps for AdStatus.
var (
	AdStatus_name = map[int32]string{
		0: "AD_STATUS_UNSPECIFIED",
		1: "AD_STATUS_ACTIVE",
		2: "AD_STATUS_SOLD",
		3: "AD_STATUS_BANNED",
		4: "AD_STATUS_INACTIVE",
	}
	AdStatus_value = map[string]int32{
		"AD_STATUS_UNSPECIFIED": 0,
		"AD_STATUS_ACTIVE":      1,
		"AD_STATUS_SOLD":        2,
		"AD_STATUS_BANNED":      3,
		"AD_STATUS_INACTIVE":    4,
	}
)

func (x AdStatus) Enum() *AdStatus {
	p := new(AdStatus)
	*p = x
	return p
}

func (x AdStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gateway_ad_v1_ad_proto_enumTypes[0].Descriptor()
}

func (AdStatus) Type() protoreflect.EnumType {
	return &file_api_gateway_ad_v1_ad_proto_enumTypes[0]
}

func (x AdStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdStatus.Descriptor instead.
func (AdStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{0}
}

// Top-level reusable message — NOT nested inside a response
// Nested messages cannot be referenced from other messages or files
type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	AuthorId      string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Price         *money.Money           `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"` // never float/double for money
	Status        AdStatus               `protobuf:"varint,7,opt,name=status,proto3,enum=api_gateway.ad.v1.AdStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // never string for timestamps
	Review        *AdReview              `protobuf:"bytes,9,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{0}
}

func (x *Ad) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ad) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Ad) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ad) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Ad) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Ad) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Ad) GetStatus() AdStatus {
	if x != nil {
		return x.Status
	}
	return AdStatus_AD_STATUS_UNSPECIFIED
}

func (x *Ad) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Ad) GetReview() *AdReview {
	if x != nil {
		return x.Review
	}
	return nil
}

type AdReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AvgReview     *decimal.Decimal       `protobuf:"bytes,1,opt,name=avg_review,json=avgReview,proto3" json:"avg_review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdReview) Reset() {
	*x = AdReview{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdReview) ProtoMessage() {}

func (x *AdReview) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdReview.ProtoReflect.Descriptor instead.
func (*AdReview) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{1}
}

func (x *AdReview) GetAvgReview() *decimal.Decimal {
	if x != nil {
		return x.AvgReview
	}
	return nil
}

type GetAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdId          string                 `protobuf:"bytes,1,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdRequest) Reset() {
	*x = GetAdRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdRequest) ProtoMessage() {}

func (x *GetAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdRequest.ProtoReflect.Descriptor instead.
func (*GetAdRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

type GetAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdResponse) Reset() {
	*x = GetAdResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdResponse) ProtoMessage() {}

func (x *GetAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdResponse.ProtoReflect.Descriptor instead.
func (*GetAdResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

// Always add pagination — never return unbounded lists
type ListAdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Status        AdStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=api_gateway.ad.v1.AdStatus" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // cursor-based is better than offset for large datasets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsRequest) Reset() {
	*x = ListAdsRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsRequest) ProtoMessage() {}

func (x *ListAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsRequest.ProtoReflect.Descriptor instead.
func (*ListAdsRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAdsRequest) GetStatus() AdStatus {
	if x != nil {
		return x.Status
	}
	return AdStatus_AD_STATUS_UNSPECIFIED
}

func (x *ListAdsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // empty string = last page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdsResponse) Reset() {
	*x = ListAdsResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdsResponse) ProtoMessage() {}

func (x *ListAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdsResponse.ProtoReflect.Descriptor instead.
func (*ListAdsResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdsResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

func (x *ListAdsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Price         *money.Money           `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdRequest) Reset() {
	*x = CreateAdRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdRequest) ProtoMessage() {}

func (x *CreateAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdRequest.ProtoReflect.Descriptor instead.
func (*CreateAdRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAdRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAdRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateAdRequest) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

type CreateAdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ad            *Ad                    `protobuf:"bytes,1,opt,name=ad,proto3" json:"ad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdResponse) Reset() {
	*x = CreateAdResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdResponse) ProtoMessage() {}

func (x *CreateAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdResponse.ProtoReflect.Descriptor instead.
func (*CreateAdResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAdResponse) GetAd() *Ad {
	if x != nil {
		return x.Ad
	}
	return nil
}

type DeactivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRequest) Reset() {
	*x = DeactivateRequest{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRequest) ProtoMessage() {}

func (x *DeactivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeactivateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AdStatus               `protobuf:"varint,1,opt,name=status,proto3,enum=api_gateway.ad.v1.AdStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateResponse) Reset() {
	*x = DeactivateResponse{}
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateResponse) ProtoMessage() {}

func (x *DeactivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_ad_v1_ad_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateResponse.ProtoReflect.Descriptor instead.
func (*DeactivateResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_ad_v1_ad_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateResponse) GetStatus() AdStatus {
	if x != nil {
		return x.Status
	}
	return AdStatus_AD_STATUS_UNSPECIFIED
}

var File_api_gateway_ad_v1_ad_proto protoreflect.FileDescriptor

const file_api_gateway_ad_v1_ad_proto_rawDesc = "" +
	"\n" +
	"\x1aapi_gateway/ad/v1/ad.proto\x12\x11api_gateway.ad.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/type/money.proto\x1a\x19google/type/decimal.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xd4\x02\n" +
	"\x02Ad\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12(\n" +
	"\x05price\x18\x06 \x01(\v2\x12.google.type.MoneyR\x05price\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.api_gateway.ad.v1.AdStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\x06review\x18\t \x01(\v2\x1b.api_gateway.ad.v1.AdReviewR\x06review\"?\n" +
	"\bAdReview\x123\n" +
	"\n" +
	"avg_review\x18\x01 \x01(\v2\x14.google.type.DecimalR\tavgReview\"#\n" +
	"\fGetAdRequest\x12\x13\n" +
	"\x05ad_id\x18\x01 \x01(\tR\x04adId\"6\n" +
	"\rGetAdResponse\x12%\n" +
	"\x02ad\x18\x01 \x01(\v2\x15.api_gateway.ad.v1.AdR\x02ad\"\x9d\x01\n" +
	"\x0eListAdsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.api_gateway.ad.v1.AdStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"b\n" +
	"\x0fListAdsResponse\x12'\n" +
	"\x03ads\x18\x01 \x03(\v2\x15.api_gateway.ad.v1.AdR\x03ads\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8a\x01\n" +
	"\x0fCreateAdRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12(\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyR\x05price\"9\n" +
	"\x10CreateAdResponse\x12%\n" +
	"\x02ad\x18\x01 \x01(\v2\x15.api_gateway.ad.v1.AdR\x02ad\"#\n" +
	"\x11DeactivateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x12DeactivateResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.api_gateway.ad.v1.AdStatusR\x06status*}\n" +
	"\bAdStatus\x12\x19\n" +
	"\x15AD_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AD_STATUS_ACTIVE\x10\x01\x12\x12\n" +
	"\x0eAD_STATUS_SOLD\x10\x02\x12\x14\n" +
	"\x10AD_STATUS_BANNED\x10\x03\x12\x16\n" +
	"\x12AD_STATUS_INACTIVE\x10\x042\xcf\x03\n" +
	"\tAdService\x12c\n" +
	"\x05GetAd\x12\x1f.api_gateway.ad.v1.GetAdRequest\x1a .api_gateway.ad.v1.GetAdResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/ads/{ad_id}\x12a\n" +
	"\aListAds\x12!.api_gateway.ad.v1.ListAdsRequest\x1a\".api_gateway.ad.v1.ListAdsResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/ads\x12g\n" +
	"\bCreateAd\x12\".api_gateway.ad.v1.CreateAdRequest\x1a#.api_gateway.ad.v1.CreateAdResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/ads\x12}\n" +
	"\n" +
	"Deactivate\x12$.api_gateway.ad.v1.DeactivateRequest\x1a%.api_gateway.ad.v1.DeactivateResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/ads/{id}/deactivate\x1a\x12\x92A\x0f\n" +
	"\radvertisementBL\x92A-\x12+\n" +
	"\n" +
	"Ad Service\x12\x18Advertisement management2\x031.0Z\x1aapi-gateway/pkg/ad/v1;adV1b\x06proto3"

var (
	file_api_gateway_ad_v1_ad_proto_rawDescOnce sync.Once
	file_api_gateway_ad_v1_ad_proto_rawDescData []byte
)

func file_api_gateway_ad_v1_ad_proto_rawDescGZIP() []byte {
	file_api_gateway_ad_v1_ad_proto_rawDescOnce.Do(func() {
		file_api_gateway_ad_v1_ad_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_ad_v1_ad_proto_rawDesc), len(file_api_gateway_ad_v1_ad_proto_rawDesc)))
	})
	return file_api_gateway_ad_v1_ad_proto_rawDescData
}

var file_api_gateway_ad_v1_ad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gateway_ad_v1_ad_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_gateway_ad_v1_ad_proto_goTypes = []any{
	(AdStatus)(0),                 // 0: api_gateway.ad.v1.AdStatus
	(*Ad)(nil),                    // 1: api_gateway.ad.v1.Ad
	(*AdReview)(nil),              // 2: api_gateway.ad.v1.AdReview
	(*GetAdRequest)(nil),          // 3: api_gateway.ad.v1.GetAdRequest
	(*GetAdResponse)(nil),         // 4: api_gateway.ad.v1.GetAdResponse
	(*ListAdsRequest)(nil),        // 5: api_gateway.ad.v1.ListAdsRequest
	(*ListAdsResponse)(nil),       // 6: api_gateway.ad.v1.ListAdsResponse
	(*CreateAdRequest)(nil),       // 7: api_gateway.ad.v1.CreateAdRequest
	(*CreateAdResponse)(nil),      // 8: api_gateway.ad.v1.CreateAdResponse
	(*DeactivateRequest)(nil),     // 9: api_gateway.ad.v1.DeactivateRequest
	(*DeactivateResponse)(nil),    // 10: api_gateway.ad.v1.DeactivateResponse
	(*money.Money)(nil),           // 11: google.type.Money
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*decimal.Decimal)(nil),       // 13: google.type.Decimal
}
var file_api_gateway_ad_v1_ad_proto_depIdxs = []int32{
	11, // 0: api_gateway.ad.v1.Ad.price:type_name -> google.type.Money
	0,  // 1: api_gateway.ad.v1.Ad.status:type_name -> api_gateway.ad.v1.AdStatus
	12, // 2: api_gateway.ad.v1.Ad.created_at:type_name -> google.protobuf.Timestamp
	2,  // 3: api_gateway.ad.v1.Ad.review:type_name -> api_gateway.ad.v1.AdReview
	13, // 4: api_gateway.ad.v1.AdReview.avg_review:type_name -> google.type.Decimal
	1,  // 5: api_gateway.ad.v1.GetAdResponse.ad:type_name -> api_gateway.ad.v1.Ad
	0,  // 6: api_gateway.ad.v1.ListAdsRequest.status:type_name -> api_gateway.ad.v1.AdStatus
	1,  // 7: api_gateway.ad.v1.ListAdsResponse.ads:type_name -> api_gateway.ad.v1.Ad
	11, // 8: api_gateway.ad.v1.CreateAdRequest.price:type_name -> google.type.Money
	1,  // 9: api_gateway.ad.v1.CreateAdResponse.ad:type_name -> api_gateway.ad.v1.Ad
	0,  // 10: api_gateway.ad.v1.DeactivateResponse.status:type_name -> api_gateway.ad.v1.AdStatus
	3,  // 11: api_gateway.ad.v1.AdService.GetAd:input_type -> api_gateway.ad.v1.GetAdRequest
	5,  // 12: api_gateway.ad.v1.AdService.ListAds:input_type -> api_gateway.ad.v1.ListAdsRequest
	7,  // 13: api_gateway.ad.v1.AdService.CreateAd:input_type -> api_gateway.ad.v1.CreateAdRequest
	9,  // 14: api_gateway.ad.v1.AdService.Deactivate:input_type -> api_gateway.ad.v1.DeactivateRequest
	4,  // 15: api_gateway.ad.v1.AdService.GetAd:output_type -> api_gateway.ad.v1.GetAdResponse
	6,  // 16: api_gateway.ad.v1.AdService.ListAds:output_type -> api_gateway.ad.v1.ListAdsResponse
	8,  // 17: api_gateway.ad.v1.AdService.CreateAd:output_type -> api_gateway.ad.v1.CreateAdResponse
	10, // 18: api_gateway.ad.v1.AdService.Deactivate:output_type -> api_gateway.ad.v1.DeactivateResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_gateway_ad_v1_ad_proto_init() }
func file_api_gateway_ad_v1_ad_proto_init() {
	if File_api_gateway_ad_v1_ad_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_ad_v1_ad_proto_rawDesc), len(file_api_gateway_ad_v1_ad_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_ad_v1_ad_proto_goTypes,
		DependencyIndexes: file_api_gateway_ad_v1_ad_proto_depIdxs,
		EnumInfos:         file_api_gateway_ad_v1_ad_proto_enumTypes,
		MessageInfos:      file_api_gateway_ad_v1_ad_proto_msgTypes,
	}.Build()
	File_api_gateway_ad_v1_ad_proto = out.File
	file_api_gateway_ad_v1_ad_proto_goTypes = nil
	file_api_gateway_ad_v1_ad_proto_depIdxs = nil
}
